
# Filepaths for input data

adm_boundaries_fp: "../data/input/DK_AdministrativeUnit/au_inspire.gpkg"
study_area_fp: "../data/processed/adm_boundaries/study_area.gpkg"
adm_area_level: "2ndOrder" # Choose "2ndOrder" for region or "3rdOrder" for municipality
study_area_name: "Region Sjælland" # Name of region in au_inspire datasæt. Must be a valid name of a Danish region or municipality

cvr_fp: "../data/input/cvr/Penhed_Region_sj.csv"


address_fp_parquet: "../data/processed/adresser/all_addresses.parquet" # "../data/input/adresser/alle_adr.parquet" 


input_address_fp: "../data/input/adresser/Adresse.parquet"
address_points_fp: "../data/input/adresser/Adressepunkt.parquet"
housenumbers_fp: "../data/input/adresser/Husnummer.parquet"

hb_codes_dict:
    doctor-gp: 862100
    dentist: 862300
    pharmacy: 477300
    kindergarten: 889130
    nursery: 889120
    school: 852010
    supermarket: 471120
    discount_supermarket: 471130
    library: 911100
    train_station: 49
    sports_facility: 93 #  931100,
