
# Filepaths for input data

adm_boundaries_fp: "../data/input/DAGI10MULTIGEOM_GPKG_HF_20250504080002/regionsinddeling.gpkg" # Data set with administrative boundaries
sub_adm_boundaries_fp: "../data/input/DAGI10MULTIGEOM_GPKG_HF_20250504080002/kommuneinddeling.gpkg" # Data set with administrative boundaries
study_area_fp: "../data/processed/adm_boundaries/study_area.gpkg"
study_area_name: "Region Sjælland" # Name of region in datasæt. Must be a valid name of a Danish region or municipality

# INPUT DATA
cvr_address_fp: "../data/input/cvr/CVR_V1_Adressering_TotalDownload_csv_Current_8.csv"
cvr_brancher_fp: "../data/input/cvr/CVR_V1_Branche_TotalDownload_csv_Current_8.csv"
cvr_penhed_fp: "../data/input/cvr/CVR_V1_Produktionsenhed_TotalDownload_csv_Current_8.csv"

input_address_fp: "../data/input/adresser/DAR_V1_Adresse_TotalDownload_csv_Current_256.csv" #"../data/input/adresser/Adresse.parquet"
address_points_fp:  "../data/input/adresser/DAR_V1_Adressepunkt_TotalDownload_csv_Current_256.csv" #"../data/input/adresser/Adressepunkt.parquet"
housenumbers_fp:  "../data/input/adresser/DAR_V1_Husnummer_TotalDownload_csv_Current_256.csv" #"../data/input/adresser/Husnummer.parquet"


#cvr_fp: "../data/input/cvr/Penhed_Region_sj.csv"

bbr_fp:  "../data/input/bbr/BBR_V1_Enhed_TotalDownload_csv_Current_263.csv"

# PROCESSED DATA
addresses_fp_all: "../data/processed/adresser/addresses-full.parquet"

# RESULTS
address_cvr_fp: "../data/results/data/all_addresses_cvr.parquet" 
address_bbr_fp: "../data/results/data/all_addresses_bbr.parquet"

destinations_combined_agg_fp: "../results/data/osm-cvr-combined-aggregated.parquet"
destinations_combined_fp: "../results/data/osm-cvr-combined.parquet"

hb_codes_dict:
    doctor-gp: 862100
    dentist: 862300
    pharmacy: 477300
    kindergarten: 889130
    nursery: 889120
    school: 852010
    supermarket: 471120
    discount_supermarket: 471130
    library: 911100
    train_station: 49
    sports_facility: 93 #  931100,

# Define here which service types to include from each source in the EXPORTED data set to be used for the analysis
# All service types will be included in the comparison of data sources
osm_export_types:
- doctor
- dentist
- pharmacy
- nursery/kindergarten
-  #school
- recreation
- shop
- train_station

cvr_export_types:
- doctor
- dentist
- pharmacy
- nursery/kindergarten
- school
- recreation
- shop
- train_station


# Mapping between service types and subcategories
sub_service_to_main: 
    doctor: 
        - doctor-gp
    dentist: 
        - dentist
    pharmacy: 
        - pharmacy
    nursery/kindergarten:
        - nursery
        - kindergarten
    school: 
        - school
    recreation:
        - library
        - sports_facility
    shop: 
        - supermarket
        - discount_supermarket
    train_station: 
        - train_station

